services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: paper_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - paper-net

  postgres:
    image: postgres:14
    container_name: paper_postgres
    restart: always
    environment:
      POSTGRES_DB: paper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/table_schema.sql:/docker-entrypoint-initdb.d/table_schema.sql
    networks:
      - paper-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: paper_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - paper-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: paper_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - paper-net

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    container_name: paper_kafka_init
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-lc"]
    command: >
      "
      echo '⏳ waiting kafka...' &&
      sleep 12 &&
      kafka-topics --bootstrap-server kafka:9092 --create
        --if-not-exists --topic paper.events.v1 --partitions 3 --replication-factor 1 &&
      echo 'topic created: paper.events.v1' &&
      kafka-topics --bootstrap-server kafka:9092 --list
      "
    networks:
      - paper-net

  backend:
    build: ./backend
    container_name: paper_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - elasticsearch
      - kafka
      - kafka-init
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    networks:
      - paper-net

  frontend:
    build: ./frontend
    container_name: paper_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - paper-net

  airflow-postgres:
    image: postgres:14
    container_name: paper_airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    networks:
      - paper-net
    restart: always

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: paper_airflow_init
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Seoul
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul

      # PostgresOperator 쓰려면 provider 필요
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    entrypoint: /bin/bash
    command: -lc "
      airflow db migrate &&
      airflow users create
        --username admin --password admin
        --firstname admin --lastname admin
        --role Admin --email admin@example.com
      || true"

    networks:
      - paper-net
    restart: "no"

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: paper_airflow_webserver
    depends_on:
      - airflow-postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Seoul
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8088:8080"
    command: webserver
    networks:
      - paper-net
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: paper_airflow_scheduler
    depends_on:
      - airflow-postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Seoul
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: scheduler
    networks:
      - paper-net
    restart: always


  namenode:
    build:
      context: ./hadoop
      dockerfile: Dockerfile
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./hadoop_data/namenode:/usr/local/hadoop/hdfs/namenode
    networks:
      - paper-net

  datanode1:
    build:
      context: ./hadoop
      dockerfile: Dockerfile
    container_name: datanode1
    hostname: datanode1
    volumes:
      - ./hadoop_data/datanode1:/usr/local/hadoop/hdfs/datanode
    networks:
      - paper-net

  datanode2:
    build:
      context: ./hadoop
      dockerfile: Dockerfile
    container_name: datanode2
    hostname: datanode2
    volumes:
      - ./hadoop_data/datanode2:/usr/local/hadoop/hdfs/datanode
    networks:
      - paper-net

  flink-jobmanager:
    image: flink:1.18.1-scala_2.12-java11
    container_name: paper_flink_jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - paper-net

  flink-taskmanager:
    image: flink:1.18.1-scala_2.12-java11
    container_name: paper_flink_taskmanager
    command: taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=4
    networks:
      - paper-net

  flink-job:
    build: ./flink
    container_name: paper_flink_job
    depends_on:
      - flink-jobmanager
      - flink-taskmanager
      - kafka
      - postgres
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - KAFKA_TOPIC=paper.events.v1
      - KAFKA_GROUP_ID=paper-flink-agg

      - JDBC_URL=jdbc:postgresql://postgres:5432/paper_db
      - JDBC_USER=postgres
      - JDBC_PASSWORD=postgres
    networks:
      - paper-net
    restart: "no"

  spark-master:
    image: spark:3.5.7
    container_name: paper_spark_master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./hadoop/core-site.xml:/opt/spark/conf/core-site.xml
      - ./hadoop/hdfs-site.xml:/opt/spark/conf/hdfs-site.xml
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master --port 7077 --webui-port 8080
    networks:
      - paper-net

  spark-worker:
    image: spark:3.5.7
    container_name: paper_spark_worker
    hostname: spark-worker
    depends_on:
      - spark-master
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./hadoop/core-site.xml:/opt/spark/conf/core-site.xml
      - ./hadoop/hdfs-site.xml:/opt/spark/conf/hdfs-site.xml
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    networks:
      - paper-net

  spark-job-kafka-to-hdfs:
    image: spark:3.5.7
    container_name: paper_spark_job_kafka_to_hdfs
    depends_on:
      - spark-master
      - spark-worker
      - kafka
      - namenode
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - KAFKA_TOPIC=paper.events.v1
      - HDFS_BASE=hdfs://namenode:9000
      - HDFS_OUT=hdfs://namenode:9000/data/events/paper_events
      - CHECKPOINT=hdfs://namenode:9000/data/checkpoints/paper_events
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./hadoop/core-site.xml:/opt/spark/conf/core-site.xml
      - ./hadoop/hdfs-site.xml:/opt/spark/conf/hdfs-site.xml
    command: >
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.7
      /opt/spark/jobs/kafka_to_hdfs.py
    networks:
      - paper-net
    restart: "no"

    
volumes:
  pgdata:
  airflow_pgdata:


networks:
  paper-net:
    driver: bridge
