services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: paper_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  postgres:
    image: postgres:14
    container_name: paper_postgres
    restart: always
    environment:
      POSTGRES_DB: paper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/table_schema.sql:/docker-entrypoint-initdb.d/table_schema.sql

  backend:
    build: ./backend
    container_name: paper_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    container_name: paper_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:
