# Generated by Django 5.2.8 on 2025-11-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField()),
                ('abstract', models.TextField()),
                ('arxiv_id', models.CharField(max_length=100, unique=True)),
                ('published', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('categories', models.CharField(max_length=200)),
                ('pdf_url', models.URLField()),
                ('citation_count', models.IntegerField(blank=True, null=True)),
                ('influential_citation_count', models.IntegerField(blank=True, null=True)),
                ('recent_interest', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
