# Generated by Django 4.2 on 2025-11-26 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='papers.paper')),
                ('context', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('alex_category_id', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestname', models.TextField()),
                ('pwd', models.TextField()),
                ('interest_1', models.TextField(null=True)),
                ('interest_2', models.TextField(null=True)),
                ('interest_3', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.TextField()),
                ('country_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YearCitation',
            fields=[
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='papers.paper')),
                ('recent_year1_count', models.IntegerField(null=True)),
                ('recent_year2_count', models.IntegerField(null=True)),
                ('recent_year3_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='arxiv_id',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='citation_count',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='influential_citation_count',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='published',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='recent_interest',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='updated',
        ),
        migrations.AddField(
            model_name='paper',
            name='alex_paper_id',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='announcement_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='citation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='locations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='open_access',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='submit',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='weekly_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='GuestCategoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.category')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.TextField()),
                ('citation_total', models.IntegerField(null=True)),
                ('main_topic_1', models.TextField(null=True)),
                ('main_topic_2', models.TextField(null=True)),
                ('main_topic_3', models.TextField(null=True)),
                ('alex_author_id', models.TextField(unique=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='papers.institution')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='papers.category'),
        ),
        migrations.AddField(
            model_name='paper',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='papers.institution'),
        ),
        migrations.CreateModel(
            name='GuestFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.guest')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper')),
            ],
            options={
                'unique_together': {('guest', 'paper')},
            },
        ),
    ]
